name: upload-to-branch
author: Grégoire Boiron (Graygzou)
description: Create a branch, push changes to it and print link to the possible PR
inputs:
  target-branch:
    description: "The target branch to push to"
    required: false
    default: "develop"
  user-name:
    description: "name of the user pushing to github"
    required: true
    default: ""
  user-mail:
    description: "email of the user pushing to github"
    required: true
    default: ""
runs:
  using: "composite"
  steps:
    - name: Config git
      run: |
        git config user.email ${{ inputs.user-mail }}
        git config user.name ${{ inputs.user-name }}
        git config pull.ff only
      shell: bash

    - name: Create branch
      id: branch-creation
      run: |
        branch="github-build-$GITHUB_RUN_ID"
        git checkout -b $branch
        echo "::set-output name=branch-name::$branch"
      shell: bash

    - name: Add changement to branch
      run: |
        git add .
        git commit -m "[ignore] Upload files generate by the job #$GITHUB_RUN_ID $GITHUB_ACTION"
        git push origin HEAD:{{ steps.branch-creation.outputs.branch-name }}
        git request-pull $GITHUB_SHA "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" ${{ inputs.target-branch }}
      shell: bash

branding:
  icon: cpu
  color: green







