name: upload-to-branch
author: Grégoire Boiron (Graygzou)
description: Create a branch, push changes to it and print link to the possible PR
inputs:
  user-name:
    description: "name of the user pushing to github"
    required: true
    default: ""
  user-email:
    description: "email of the user pushing to github"
    required: true
    default: ""
  target-branch:
    description: "The target branch to push to"
    required: false
    default: "develop"
  add-pattern:
    description: "regex to using when adding files for next commit"
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - name: Config git
      run: |
        git config user.email ${{ inputs.user-email }}
        git config user.name ${{ inputs.user-name }}
        git config pull.ff only
      shell: bash

    - name: Checkout the branch
      id: branch-checkout
      run: |
        git checkout $(git show-ref --verify --quiet refs/heads/${{ inputs.target-branch }} || echo '-b') ${{ inputs.target-branch }}
      shell: bash

    - name: Add changements to branch
      run: |
        git add ${{ inputs.add-pattern }}
        git commit -m "[skip ci] Files generate by the $GITHUB_WORKFLOW workflow (run #$GITHUB_RUN_ID)"
        git checkout -- .
      shell: bash

    # $(git show-ref --verify --quiet refs/heads/${{ inputs.target-branch }} && echo 'git pull')
    - name: Push changements to branch
      run: |
        git fetch
        git rebase HEAD:${{ inputs.target-branch }} || true
        git pull --rebase || true
        git push origin HEAD:${{ inputs.target-branch }}
      shell: bash

    - name: Create PR link if not develop
      run: git request-pull $GITHUB_SHA "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" ${{ inputs.target-branch }}
      shell: bash

branding:
  icon: cpu
  color: green







