name: file-changed
author: Grégoire Boiron (Graygzou)
description: Use image magick to resize images in a given folder.
inputs:
  original-folder:
    description: "folder where the original images are located."
    required: true
    default: "jekyll/assets/"
  extension:
    description: "extension of the images to convert"
    required: true
    default: "jpg"
runs:
  using: "composite"
  steps:
    - name: Download package
      run: |
        echo "::group::download imagemagick"
        wget https://www.imagemagick.org/download/ImageMagick.tar.gz
        tar xf ImageMagick.tar.gz
        echo "::endgroup::"
      shell: bash

    - name: Install packages
      run: |
        echo "::group::install imagemagick"
        cd ImageMagick-7*
        ./configure
        make
        sudo make install
        sudo ldconfig /usr/local/lib
        cd ..
        echo "::endgroup::"
      shell: bash

    - name: Version
      run: identify -version
      shell: bash

    - name: Make script executables
      run: chmod +x ./.github/scripts/*/*.sh
      shell: bash

      # Try to find if any file matching the provided extension
    - name: Run script
      run: |
        echo "::group::use imagemagick"
        ./.github/scripts/generation/image-magick.sh ${{ inputs.extension }}
        echo "::endgroup::"
      shell: bash

    - name: Remove package installed
      run: |
        echo "::group::remove imagemagick files"
        rm -vrf ImageMagick-7*
        rm -vrf ImageMagick.tar.gz
        echo "::endgroup::"
      shell: bash

branding:
  icon: cpu
  color: green