name: file-changed
author: Grégoire Boiron (Graygzou)
description: Use image magick to resize images in a given folder.
inputs:
  original-folder:
    description: "folder where the original images are located."
    required: false
    default: "jekyll/assets/"
  extension:
    description: "extension of the images to convert"
    required: false
    default: ""
  sha:
    description: "the sha in which to look up files"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Download package
      run: |
        echo "::group::download imagemagick"
        wget https://www.imagemagick.org/download/ImageMagick.tar.gz
        tar xf ImageMagick.tar.gz
        echo "::endgroup::"
      shell: bash

    - name: Install packages
      run: |
        echo "::group::install imagemagick"
        cd ImageMagick-7*
        ./configure
        make
        sudo make install
        sudo ldconfig /usr/local/lib
        cd ..
        echo "::endgroup::"
      shell: bash

    - name: Version
      run: identify -version
      shell: bash

    - name: Make script executables
      run: chmod +x ./.github/scripts/*/*.sh
      shell: bash

      # Try to find if any file matching the provided extension
    - name: Run script with folder and extension
      run: |
        echo "::group::use imagemagick"
        PATH=$(find ${{ inputs.original-folder }} -regex ".*\[[r|c][0-9]+x[0-9]+\]+\.${{ inputs.extension }}$")
        echo $PATH
        ./.github/scripts/generation/image-magick.sh $PATH
        echo "::endgroup::"
      shell: bash
      if: ${{ inputs.extension != "" }}
      
    - name: Run script with github sha
      run: |
        echo "::group::use imagemagick"
        git log --name-only -n 1 ${{ inputs.sha }} --pretty=format:%b > last-commit.txt;
        PATH=$(find last-commit.txt -regex ".*\[[r|c][0-9]+x[0-9]+\]+\.[png|jpg]$")
        echo $PATH
        ./.github/scripts/generation/image-magick.sh $PATH
        echo "::endgroup::"
      shell: bash
      if: ${{ inputs.sha != "" }}

    - name: Remove package installed
      run: |
        echo "::group::remove imagemagick files"
        rm -vrf ImageMagick-7*
        rm -vrf ImageMagick.tar.gz
        echo "::endgroup::"
      shell: bash

branding:
  icon: cpu
  color: green
