dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"

# reduce log clutter
cache: bundler  # caching bundler gem packages will speed up build

before_install:
  - sudo apt-get install pngquant
  - gem install bundler
  - pip install -r requirements.txt
  - (cd scripts && find -name "*.py" -exec python {} ${GITHUB_API_TOKEN} \;)

# command to install dependencies
# This was obtained by running $pip freeze > requirements.txt
install:
  - (cd jekyll && gem update bundler)
  - (cd jekyll && bundle check || bundle install)

before_script:
  - chmod +x scripts/*.sh

script:
  - ./scripts/cibuild.sh
  - ./scripts/postprocess.sh
  - bundle exec htmlproofer ../site --url-ignore "https://www.linkedin.com/in/gregoire-boiron/,https://www.latecoere.aero/en/"

branches:
  except:
  - live

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

deploy:
  provider: pages
  verbose: true
  local_dir: ./jekyll/site
  skip_cleanup: true
  github_token: ${GITHUB_DEPLOY_TOKEN}  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  target_branch: master
  email: ${GITHUB_BOT_MAIL}
  name: ${GITHUB_BOT_NAME}
  on:
    branch: develop


# command to run tests
#script:
#  - py.test -v --color=yes --exitfirst --showlocals --durations=5
#
#after_success:
#  - python websiteGen.py GITHUB_API_TOKEN
