dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"

env:
  global:
    - JEKYLL_ENV=production

# reduce log clutter
cache: bundler

before_install:
  - gem install bundler
  - (cd scripts && find -name "*.py" -exec python {} ${GITHUB_API_TOKEN} \;)
  - (cd jekyll && gem update bundler)

# command to install dependencies
# This was obtained by running $pip freeze > requirements.txt
install:
  - pip install -r requirements.txt
  - (cd jekyll && bundle check || bundle install)

script:
  - set -e # Enable error reporting to the console
  - (cd jekyll && bundle exec jekyll build --destination site)

branches:
  except:
  - live

deploy:
  provider: pages
  verbose: true
  local_dir: ./jekyll/site
  skip_cleanup: true
  github_token: ${GITHUB_DEPLOY_TOKEN}  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  target_branch: master
  on:
    branch: develop


# command to run tests
#script:
#  - py.test -v --color=yes --exitfirst --showlocals --durations=5
#
#after_success:
#  - python websiteGen.py GITHUB_API_TOKEN
