dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"

addons:
  chrome: stable # make sure you have Chrome available
  apt:
    packages:
      - libcurl4-openssl-dev

branches:
  except:
    - master

# reduce log clutter
cache: bundler  # caching bundler gem packages will speed up build

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# pip install -r requirements.txt => command to install dependencies
# This was obtained by running $pip freeze > requirements.txt
before_install:
  - nvm install 12
  - node --version
  - npm --version
  - nvm --version
  - npm install -g @lhci/cli@0.3.x
  - gem install bundler
  - pip install -r requirements.txt
  - (cd scripts && python mainSvgGen.py ${GITHUB_API_TOKEN} \;)
  - (cd scripts && python githubProjectGen.py ${GITHUB_API_TOKEN} \;)

install:
  - (cd jekyll && gem update bundler)
  - (cd jekyll && bundle check || bundle install)

before_script:
  - chmod +x scripts/*.sh

script:
  - (cd scripts && python grammarContentCheck.py ${GRAMMAR_BOT_TOKEN} \;)
  - ./scripts/build.sh
  - ./scripts/beforeinstall.sh
  - ./scripts/cibuild.sh

after_failure:
  - curl https://www.teleconsole.com/get.sh | sh
  - teleconsole

deploy:
  provider: pages
  verbose: true
  local_dir: ./jekyll/site
  skip_cleanup: true
  github_token: ${GITHUB_DEPLOY_TOKEN}  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  target_branch: master
  email: ${GITHUB_BOT_MAIL}
  name: ${GITHUB_BOT_NAME}
  on:
    branch: develop

# See travis job cycle: https://docs.travis-ci.com/user/job-lifecycle
after_deploy:
  - (cd scripts && python getAllWebsitePages.py 0 "../jekyll/site/sitemap.xml" \;)
  - lhci healthcheck --fatal --checks=githubToken
  - lhci autorun --config=./lighthouserc.json