name: html-proofer
author: Grégoire Boiron (Graygzou)
description: 
inputs:
  bundle-path:
    description: "Path that will help cache bundle dependencies."
    required: true
    default: 'vendor/bundle'
  bundle-folder:
    description: "Directory where to install bundler and run html-proofer"
    required: true
    default: './'
  html-relative-folder:
    description: "Directory containing all the generated html files."
    required: false
    default: './'
  url-ignore:
    description: "list of urls that needs to be ignore during the test."
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    # required to avoid SSL errors
    - name: install libcurl4-openssl
      run: sudo apt-get install libcurl4-openssl-dev
      shell: bash

    - name: install-bundler
      run: gem install bundler
      shell: bash

    - name: setup-bundler-correctly
      working-directory: ${{ inputs.bundle-folder }}
      run: |
        echo "::group::bundle commands"
        bundle update --bundler
        bundle config path ${{ inputs.bundle-path }}
        bundle install --jobs 4 --retry 3
        echo "::endgroup::"
      shell: bash

    - name: execute-html-proofer
      working-directory: ${{ inputs.bundle-folder }}
      run: |
        TYPHOEUS_CONFIG='{ "headers": { "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/81.0" } }'
        echo ${{ fromJSON($TYPHOEUS_CONFIG) }}
        bundle exec htmlproofer --url-ignore ${{ inputs.url-ignore }} --typhoeus-config ${{ fromJSON($TYPHOEUS_CONFIG) }} ${{ inputs.html-relative-folder }}
      shell: bash

branding:
  icon: cpu
  color: orange