name: html-proofer
author: Grégoire Boiron (Graygzou)
description: 
inputs:
  bundle-path:
    description: "Path that will help cache bundle dependencies."
    required: true
    default: 'vendor/bundle'
  bundle-folder:
    description: "Directory where to install bundler and run html-proofer"
    required: true
    default: './'
  html-relative-folder:
    description: "Directory containing all the generated html files."
    required: false
    default: './'
  url-ignore:
    description: "list of urls that needs to be ignore during the test."
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: install-bundler
      run: gem install bundler
      shell: bash

    - name: setup-bundler-correctly
      working-directory: ${{ inputs.bundle-folder }}
      run: |
        echo "::group::bundle commands"
        bundle update --bundler
        bundle config path ${{ inputs.bundle-path }}
        bundle install --jobs 4 --retry 3
        echo "::endgroup::"
      shell: bash

    - name: execute-html-proofer
      run: bundle exec htmlproofer --url-ignore ${{ inputs.url-ignore }} ${{ inputs.html-relative-folder }}
      shell: bash

branding:
  icon: cpu
  color: orange