name: Webp creation
author: Grégoire Boiron (Graygzou)
description: Duplicate and generate webp images from original ones
inputs:
  contains_png:
    description: "if the last commits contains pngs"
    required: true
    default: false
runs:
  using: "composite"
  steps:
    - name: Setup bundler correctly
      run: |
        echo $INPUT_CONTAINS_PNG
        if [[ $INPUT_CONTAINS_PNG == false ]]
          echo "::group::bundle commands"
          sudo apt-get install webp
          echo "::endgroup::"
        fi
      shell: bash

    - name: Install bundler
      run: |
        if [[ $INPUT_CONTAINS_PNG ]] ; then
          jpgResult=$( ./scripts/helpers/file-changed-in-last-commit.sh "*\.jpg$" )
          pngResult=$( ./scripts/helpers/file-changed-in-last-commit.sh "*\.png$" )
          echo $jpgResult
          echo $pngResult
        else
          echo "contains_png == false !" 
        fi
      shell: bash

branding:
  icon: cpu
  color: orange