name: Webp creation
author: Grégoire Boiron (Graygzou)
description: Duplicate and generate webp images from original ones
inputs:
  target-folder:
    description: "folder where the webp images will be saved"
    required: false
    default: "jekyll/assets/webp/"
  original-folder:
    description: "folder where the original images are located."
    required: true
    default: "jekyll/assets/originals"
  extensions-regex:
    description: "image extensions that will be converted into webp"
    required: true
    default: ""
outputs:
  webp-folder:
    description: "folder where the converted webp image will be saved."
    value: ${{ steps.finalize-images.outputs.result-folder }}
    #default: "webp/"
runs:
  using: "composite"
  steps:
    - name: Setup bundler correctly
      run: |
        echo "::group::bundle commands"
        sudo apt-get install webp
        sudo apt-get install rename
        echo "::endgroup::"
      shell: bash

    - name: Make script executables
      run: chmod +x ./.github/scripts/*/*.sh
      shell: bash

    # Use cwebp to encode all asset images except for the folder ./originals. 
    # for more info on cwebp see https://developers.google.com/speed/webp/docs/precompiled
    - name: 
      run: |
        echo "::group::run cwebp command"
        echo "Start running cwebp for webp image creation"
        ./.github/scripts/generation/webp.sh ${{ inputs.original-folder }} ${{ inputs.target-folder }}
        echo "::endgroup::"
      shell: bash

branding:
  icon: edit
  color: orange
