name: Webp creation
author: Grégoire Boiron (Graygzou)
description: Duplicate and generate webp images from original ones
inputs:
  contains-jpg-or-png:
    description: "true if the last commits contains png or jpg files. false otherwise."
    required: false
    default: true
  target-folder:
    description: "folder where the converted webp image will be saved."
    required: false
    default: "webp/"
runs:
  using: "composite"
  steps:
    - name: Check pre-condition
      run: |
        echo ${{ inputs.contains-jpg-or-png }}
        echo ${{ inputs.target-folder }}
        if [[ ${{ inputs.contains-jpg-or-png }} == false ]] ; then
          echo "No .jpg or .png pushed. Skip job ⏸️"
          exit 0
        else
          echo ".jpg or .png detected in last push. Start ▶️"
        fi
      shell: bash

    - name: Setup bundler correctly
      run: |
        if [[ ${{ inputs.contains-jpg-or-png }} ]] ; then
          echo "::group::bundle commands"
          sudo apt-get install webp
          echo "::endgroup::"
        fi
      shell: bash

    # Remove the old directory and create a new one if necessary
    - name: Clean previous folder
      run: |
        echo "::group::create webp folder"
        echo "Remove all webp folder"
        if [[ -d "${{ inputs.contains-jpg-or-png }}" ]]; then
          rm -vrf "${{ inputs.contains-jpg-or-png }}"
        fi
        mkdir "${{ inputs.contains-jpg-or-png }}"
        echo "::endgroup::"
      shell: bash

    # Use cwebp to encode all asset images except for the folder ./originals. 
    # for more info on cwebp see https://developers.google.com/speed/webp/docs/precompiled
    - name: 
      run: |
        echo "::group::run cwebp command"
        echo "Start running cwebp for webp image creation"
        find jekyll/assets/ -type d -path jekyll/assets/originals -prune -o -regex '.*\.\(jpg\|png\)' -print -exec cwebp {} -o {}.webp \;
        echo "::endgroup::"
      shell: bash

    # Move images to another directory and re name it correctly.
    - name:
      run: | 
        echo "::group::rename_webp_images"
        echo "Renamed new images and move them in a separated folder"
        find jekyll/assets/ -name "*.webp" -exec mv {} "${{ inputs.contains-jpg-or-png }}/" \;
        cd "${{ inputs.contains-jpg-or-png }}/"
        rename -v 's/.png.webp|.jpg.webp/.webp/gi' *.webp \;
        find . -regex '.*\.\(png\.webp\|jpg\.webp\)' -exec rm -v {} \;
        cd ../../..
        echo "::endgroup::"
      shell: bash

branding:
  icon: edit
  color: orange