name: Webp creation
author: Grégoire Boiron (Graygzou)
description: Duplicate and generate webp images from original ones
inputs:
  original-folder:
    description: "folder where the original images are located."
    required: true
    default: "jekyll/assets/originals"
  extensions:
    description: "image extensions that will be converted into zebp"
    required: true
    default: []
outputs:
  webp-folder:
    description: "folder where the converted webp image will be saved."
    value: ${{ steps.rename-and-move-webp-images.outputs.result-folder }}
    #default: "webp/"
runs:
  using: "composite"
  steps:
    - name: Setup bundler correctly
      run: |
        echo "::group::bundle commands"
        sudo apt-get install webp
        echo "::endgroup::"
      shell: bash

    # Remove the old directory and create a new one if necessary
    - name: Clean previous folder
      run: |
        echo "::group::create webp folder"
        echo "Remove all webp folder"
        if [[ -d "${{ inputs.target-folder }}" ]]; then
          rm -vrf "${{ inputs.target-folder }}"
        fi
        mkdir "${{ inputs.target-folder }}"
        echo "::endgroup::"
      shell: bash

    # Use cwebp to encode all asset images except for the folder ./originals. 
    # for more info on cwebp see https://developers.google.com/speed/webp/docs/precompiled
    - name: 
      run: |
        echo "::group::run cwebp command"
        echo "Start running cwebp for webp image creation"
        find jekyll/assets/ -type d -path ${{ original-folder }} -prune -o -regex ".*\.\(${{ join(inputs.extensions, '\|') }}\)" -print -exec cwebp {} -o {}.webp \;
        echo "::endgroup::"
      shell: bash

    # TODO: Break those into two steps
    # Move images to another directory and re name it correctly.
    - name: rename-and-move-webp-images
      run: | 
        echo "::group::rename_webp_images"
        echo "Renamed new images and move them in a separated folder"
        find jekyll/assets/ -name "*.webp" -exec mv {} "${{ inputs.target-folder }}/" \;
        cd "${{ inputs.target-folder }}/"
        rename -v 's/.png.webp|.jpg.webp/.webp/gi' *.webp \;
        find . -regex '.*\.\(png\.webp\|jpg\.webp\)' -exec rm -v {} \;
        cd ../../..
        echo "::set-output name=result-folder::$(echo ${{ inputs.target-folder }}/)"
        echo "::endgroup::"
      shell: bash

branding:
  icon: edit
  color: orange
