name: Webp creation
author: Grégoire Boiron (Graygzou)
description: Duplicate and generate webp images from original ones
inputs:
  contains_png:
    description: "if the last commits contains pngs"
    required: true
    default: false
runs:
  using: "composite"
  steps:
    - name: Setup bundler correctly
      run: |
        if [[ ${{ contains_png == false }} ]]
        echo "::group::bundle commands"
        sudo apt-get install webp
        echo "::endgroup::"
      shell: bash

    - name: Install bundler
      run: |
        if [[ ${{ contains_png }} ]] ; then
          jpgResult=$( ./scripts/helpers/file-changed-in-last-commit.sh "*\.jpg$" )
          pngResult=$( ./scripts/helpers/file-changed-in-last-commit.sh "*\.png$" )
        else
          echo "contains_png == false !" 
        fi
      shell: bash

branding:
  icon: cpu
  color: orange