name: Webp creation
author: Grégoire Boiron (Graygzou)
description: Duplicate and generate webp images from original ones
inputs:
  contains_png:
    description: "true if the last commits contains png files. false otherwise."
    required: true
    default: false
  contains_jpg:
    description: "true if the last commits contains jpg files. false otherwise."
    required: true
    default: false
runs:
  using: "composite"
  steps:
    - name: Setup bundler correctly
      run: |
        echo $INPUT_CONTAINS_JPG
        echo $INPUT_CONTAINS_PNG
        if [[ $INPUT_CONTAINS_PNG || $INPUT_CONTAINS_JPG ]] ; then
          echo "::group::bundle commands"
          sudo apt-get install webp
          echo "::endgroup::"
        fi
      shell: bash

    - name: Install bundler
      run: |
        if [[ $INPUT_CONTAINS_PNG || $INPUT_CONTAINS_JPG ]] ; then
          echo $jpgResult
          echo $pngResult
        else
          echo "No .jpg or .png pushed. Skip job ⏭️" 
        fi
      shell: bash

branding:
  icon: cpu
  color: orange