name: Webp creation
author: Grégoire Boiron (Graygzou)
description: Duplicate and generate webp images from original ones
inputs:
  target-folder:
    description: "folder where the webp images will be saved"
    required: false
    default: "webp/"
  original-folder:
    description: "folder where the original images are located."
    required: true
    default: "jekyll/assets/originals"
  extensions-regex:
    description: "image extensions that will be converted into webp"
    required: true
    default: ""
outputs:
  webp-folder:
    description: "folder where the converted webp image will be saved."
    value: ${{ steps.finalize-images.outputs.result-folder }}
    #default: "webp/"
runs:
  using: "composite"
  steps:
    - name: Setup bundler correctly
      run: |
        echo "::group::bundle commands"
        sudo apt-get install webp
        sudo apt-get install rename
        echo "::endgroup::"
      shell: bash

    # Use cwebp to encode all asset images except for the folder ./originals. 
    # for more info on cwebp see https://developers.google.com/speed/webp/docs/precompiled
    - name: 
      run: |
        echo "::group::run cwebp command"
        echo "Start running cwebp for webp image creation"
        find jekyll/assets/ -type d -path ${{ inputs.original-folder }} -prune -o -regex ".*\.\(${{ inputs.extensions-regex }}\)" -print -exec cwebp {} -o {}.webp \;
        echo "::endgroup::"
      shell: bash

    # TODO: Break those into two steps
    # Move images to another directory and re name it correctly.
    - name: Rename and move webp images
      id: finalize-images
      run: | 
        echo "::group::rename_webp_images"
        echo "Renamed new images and move them in a separated folder"
        find jekyll/assets/ -name "*.webp" -exec mv {} "${{ inputs.target-folder }}/" \;
        cd "${{ inputs.target-folder }}/"
        rename -v "s/(${{ inputs.extensions-regex }}).webp/.webp/gi" *.webp \;
        find . -regex '.*\.\(${{ inputs.extensions-regex }}\.webp\)' -exec rm -v {} \;
        cd ../../..
        echo "::set-output name=result-folder::$(echo ${{ inputs.target-folder }}/)"
        echo "::endgroup::"
      shell: bash

branding:
  icon: edit
  color: orange
