name: resize-images
author: Grégoire Boiron (Graygzou)
description: Use image magick to resize images in a given folder. Required image magick installed. See install-imagemagick action.
inputs:
  images-names-file:
    description: "file containing path of all images to resize"
    required: true
    default: ""
  destination-folder:
    description: "folder that will hold transformed images"
    required: false
    default: "jekyll/assets/output"

runs:
  using: "composite"
  steps:

    - name: Make script executables
      run: chmod +x ./.github/scripts/*/*.sh
      shell: bash

      # Try to find if any file matching the provided extension
    - name: Run script with folder and extension
      run: |
        echo "::group::use imagemagick"
        echo ${{ inputs.images-names-file }}
        ./.github/scripts/generation/image-magick.sh ${{ inputs.images-names-file }} ${{ inputs.destination-folder }} 
        echo "::endgroup::"
      shell: bash

branding:
  icon: cpu
  color: green
