# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Default configuration
# See https://jekyllrb.com/docs/configuration/default/ for more information
source: .
safe: true
highlighter: rouge
lsi: false
incremental: false

permalink: date
paginate_path: /page:num
timezone: null

quiet: false
verbose: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Grégoire Boiron
profil_description: Programmer Generalist at iLLOGIKA
email: gregoire.boiron@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Grégoire Boiron's personal site.
  Contains my portfolio, my projects and my own blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
social_tags:
  - name: twitter
    path: https://twitter.com/GrayGzou
  - name: github
    path: https://github.com/Graygzou
  - name: linkedin
    path: https://www.linkedin.com/in/gregoire-boiron/
  - name: gamejolt
    path: https://gamejolt.com/@GrayGzou
  - name: itch-dot-io
    path: https://graygzou.itch.io/

# Build settings
markdown: kramdown
#theme: minima # Should change that ?
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
