name: install
author: Grégoire Boiron (Graygzou)
description: Proceed to the installation of ruby and bundler
inputs:
  bundle_path:
    description: "Path that will help cache bundle dependencies"
    required: true
    default: 'vendor/bundle'
runs:
  using: "composite"
  steps:
    - name: Install bundler
      run: |
        echo "::group::install bundler"
        gem install bundler
        echo "::endgroup::"
      shell: bash

    - name: Setup bundler correctly
      working-directory: ./jekyll
      run: |
        echo "::group::bundle commands"
        bundle update --bundler
        bundle config path $INPUT_BUNDLE_PATH
        bundle install --jobs 4 --retry 3
        echo "::endgroup::"
      shell: bash

branding:
  icon: cpu
  color: orange