name: install-imagemagick
author: Grégoire Boiron (Graygzou)
description: Install image magick at a given location.
inputs:
  install-folder:
    description: "folder where image magick will be installed"
    required: false
    default: "imagemagick/"
    
runs:
  using: "composite"
  steps:
    - name: Download package
      run: |
        echo "::group::download imagemagick"
        mkdir ${{ inputs.install-folder }}
        cd ${{ inputs.install-folder }}
        wget https://www.imagemagick.org/download/ImageMagick.tar.gz
        tar xf ImageMagick.tar.gz
        echo "::endgroup::"
      shell: bash

    - name: Install packages
      run: |
        echo "::group::install imagemagick"
        cd ${{ inputs.install-folder }}/ImageMagick-7*
        ./configure
        make
        sudo make install
        sudo ldconfig /usr/local/lib
        cd
        echo "::endgroup::"
      shell: bash

    - name: Version
      run: identify -version
      shell: bash

branding:
  icon: cpu
  color: green
