name: jekyll-build
author: Grégoire Boiron (Graygzou)
description: Proceed to the installation of ruby and bundler
inputs:
  bundle-path:
    description: "Path that will help cache bundle dependencies"
    required: true
    default: 'vendor/bundle'
  project-folder:
    description: "directory containing all the jekyll source files."
    required: true
    default: './'
  environment:
    description: "Use a specific environment value in the build. Default is production."
    required: false
    default: 'production'
  destination-relative-folder:
    description: "The directory where Jekyll will write files."
    required: false
    default: 'output'
  show-draft:
    description: "Process and render draft posts."
    required: false
    default: 'false'
  unpublished:
    description: "Render posts that were marked as unpublished."
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Install bundler
      run: gem install bundler
      shell: bash

    - name: Setup bundler correctly
      working-directory: ${{ inputs.project-folder }}
      run: |
        echo "::group::bundle commands"
        bundle update --bundler
        bundle config path ${{ inputs.bundle-path }}
        bundle install --jobs 4 --retry 3
        echo "::endgroup::"
      shell: bash

    - name: Install bundler
      working-directory: ${{ inputs.project-folder }}
      run: bundle exec jekyll build JEKYLL_ENV=${{ inputs.environment }} --destination ${{ inputs.destination-relative-folder }}
      shell: bash

branding:
  icon: cpu
  color: orange