# This is a basic workflow to help you get started with Actions

name: Archive site

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      # See https://github.com/marketplace/actions/wayback-machine for github action
      # And https://github.com/wabarc/wayback#configuration-parameters
      # And https://github.com/wabarc/on-github
      #
      # or https://archive.org/services/docs/api/internetarchive/cli.html#getting-started to use the python library
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
