#############################################################################
# Grégoire Boiron <gregoire.boiron@gmail.com>
# Copyright (c) 2018-2021 Grégoire Boiron  All Rights Reserved.
#############################################################################

name: Compress images

on:
  workflow_run:
    workflows: ["Convert to webp"]
    branches: [develop]
    types: 
      - completed

  workflow_dispatch:
    inputs:
      create-request-pull:
        description: 'Create request pull'
        required: true
        default: 'false'

jobs:
  compress:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Github checkout
        uses: actions/checkout@v2

      - name: Make script executables
        run: chmod +x scripts/*/*.sh

      - name: pngquant-png-compression
        run: ./scripts/integration/pngquant-compression.sh

      - name: guetzli-jpg-compression
        run: ./scripts/integration/guetzli-compression.sh

      - name: Upload compressed image
        uses: actions/upload-artifact@v1
        with:
          name: compressed-image
          path: jekyll/site/assets/project-images/

      - name: Test
        run: |
          echo github.ref
          echo $GITHUB_REF

      - name: Upload to branch
        uses: ./.github/actions/upload-to-branch
        with:
          target-branch: github.ref
          user-name: ${{ secrets.BOT_ACCOUNT_NAME }}
          user-email: ${{ secrets.BOT_ACCOUNT_MAIL }}
        if: ${{ github.event.inputs.create-request-pull == 'true' }}
