#############################################################################
# Grégoire Boiron <gregoire.boiron@gmail.com>
# Copyright (c) 2018-2021 Grégoire Boiron  All Rights Reserved.
#############################################################################

name: Compress images

on:
  workflow_run:
    workflows: ["Convert to webp"]
    branches: [develop]
    types: 
      - completed

  workflow_dispatch:
    inputs:
      create-request-pull:
        description: 'Create request pull'
        required: true
        default: 'false'
      use-sha:
        description: 'Use GitHub sha'
        required: true
        default: 'true'
      target-branch:
        description: 'Branch to upload to'
        required: false
        default: 'develop'

jobs:
  compress-png:
    runs-on: ubuntu-latest
    env:
      TARGET_FOLDER: "jekyll/assets/compressed"
    defaults:
      run:
        shell: bash
    steps:
      - name: Github checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 3
          ref: workflow-${{ github.sha }}

      - name: Build file from github sha
        run: |
          git fetch --depth 2
          git log --name-only -n 1 ${{ github.sha }} --pretty="format:" > last-commit.txt
          grep -E '.*\.png' last-commit.txt | sort --unique > image-paths.txt || true
        shell: bash
        if: ${{ github.event_name == 'workflow_run' || github.event.inputs.use-sha == 'true' }}
        
      - name: Appends pushed resized file from current ref
        run: |
          git log --name-only -n 2 --pretty="format:" > last-commit.txt
          grep -E '.*(\[(r|c)[0-9]+x[0-9]+\])+\.png' last-commit.txt | sort --unique >> image-paths.txt || true
        shell: bash
        if: ${{ github.event_name == 'workflow_run' || github.event.inputs.use-sha == 'true' }}

      - name: Create the env variable based on .txt file
        run: |
          cat image-paths.txt
          wc -m < image-paths.txt
          char_number=$(wc -m < image-paths.txt)
          echo "action_state=$char_number" >> $GITHUB_ENV

      - name: Install
        run: |
          echo "::group::installation"
          echo "${{ env.action_state }}"
          sudo apt-get install pngquant
          echo "::endgroup::"
        if: ${{ env.action_state != 0 }}
        
      - name: Run
        run: |
          echo "::group::run_pngquant"
          chmod +x ./.github/scripts/*/*.sh
          ./.github/scripts/integration/pngquant-compression.sh image-paths.txt ${{ env.TARGET_FOLDER }}
          echo "::endgroup::"
        if: ${{ env.action_state != 0 }}

      - name: Upload compressed image
        uses: actions/upload-artifact@v2
        with:
          name: compressed-png
          path: ${{ env.TARGET_FOLDER }}
        if: ${{ env.action_state != 0 }}

      - name: Upload to branch workflow_dispatch
        uses: ./.github/actions/upload-to-branch
        with:
          target-branch: ${{ github.event.target-branch }}
          user-name: ${{ secrets.BOT_ACCOUNT_NAME }}
          user-email: ${{ secrets.BOT_ACCOUNT_MAIL }}
        if: ${{ success() && github.event_name != 'workflow_run' && github.event.inputs.create-request-pull == 'true' }}

      - name: Upload to branch on workflow_run
        uses: ./.github/actions/upload-to-branch
        with:
          target-branch: workflow-${{ github.sha }}
          add-pattern: "*.png"
          user-name: ${{ secrets.BOT_ACCOUNT_NAME }}
          user-email: ${{ secrets.BOT_ACCOUNT_MAIL }}
        if: ${{ success() && github.event_name == 'workflow_run' && env.action_state != 0 }}
    
  compress-jpg:
    runs-on: ubuntu-latest
    env:
      TARGET_FOLDER: "jekyll/assets/compressed"
    defaults:
      run:
        shell: bash
    steps:
      - name: Github checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          ref: workflow-${{ github.sha }}

      - name: Build file from github sha
        run: |
          git fetch --depth 2
          git log --name-only -n 1 ${{ github.sha }} --pretty="format:" > last-commit.txt
          grep -E '.*\.jpg' last-commit.txt > image-paths.txt || true
        shell: bash
        if: ${{ github.event_name == 'workflow_run' || github.event.inputs.use-sha == 'true' }}
        
      - name: Appends pushed resized file from current ref
        run: |
          git log --name-only -n 1 --pretty="format:" > last-commit.txt
          grep -E '.*(\[(r|c)[0-9]+x[0-9]+\])+\.jpg' last-commit.txt >> image-paths.txt || true
        shell: bash
        if: ${{ github.event_name == 'workflow_run' || github.event.inputs.use-sha == 'true' }}
        
      - name: Create the env variable based on .txt file
        run: |
          cat image-paths.txt
          wc -m < image-paths.txt
          char_number=$(wc -m < image-paths.txt)
          echo "action_state=$char_number" >> $GITHUB_ENV

      - name: Download
        run: |
          echo "::group::download"
          curl -L https://github.com/google/guetzli/archive/v1.0.1.tar.gz | tar zx
          sudo apt-get install libpng-dev
          echo "::endgroup::"
        if: ${{ env.action_state != 0 }}
          
      - name: Install
        run: |
          echo "::group::installation"
          cd guetzli-1.0.1 && make
          echo "::endgroup::"
        if: ${{ env.action_state != 0 }}
          
      - name: Run
        run: |
          echo "::group::run_guestzli"
          chmod +x ./.github/scripts/*/*.sh
          ./.github/scripts/integration/guetzli-compression.sh image-paths.txt ${{ env.TARGET_FOLDER }}
          echo "::endgroup::"
        
      - name: Upload compressed image
        uses: actions/upload-artifact@v2
        with:
          name: compressed-jpg
          path: ${{ env.TARGET_FOLDER }}
        if: ${{ env.action_state != 0 }}
          
      - name: Upload to branch workflow_dispatch
        uses: ./.github/actions/upload-to-branch
        with:
          target-branch: ${{ github.event.target-branch }}
          user-name: ${{ secrets.BOT_ACCOUNT_NAME }}
          user-email: ${{ secrets.BOT_ACCOUNT_MAIL }}
        if: ${{ success() && github.event_name != 'workflow_run' && github.event.inputs.create-request-pull == 'true' }}
        
      - name: Upload to branch on workflow_run
        uses: ./.github/actions/upload-to-branch
        with:
          target-branch: workflow-${{ github.sha }}
          add-pattern: "*.jpg"
          user-name: ${{ secrets.BOT_ACCOUNT_NAME }}
          user-email: ${{ secrets.BOT_ACCOUNT_MAIL }}
        if: ${{ success() && github.event_name == 'workflow_run' && env.action_state != 0 }}
