#############################################################################
# Grégoire Boiron <gregoire.boiron@gmail.com>
# Copyright (c) 2018-2021 Grégoire Boiron  All Rights Reserved.
#############################################################################

name: Compress images

on:
  workflow_run:
    workflows: ["Convert to webp"]
    branches: [develop]
    types: 
      - completed

  workflow_dispatch:
    inputs:
      create-request-pull:
        description: 'Create request pull'
        required: true
        default: 'false'
      target-branch:
        description: 'Branch to upload to'
        required: false
        default: 'develop'

jobs:
  compress-png:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Github checkout
        uses: actions/checkout@v2

      - name: Install
        run: |
          echo "::group::installation"
          sudo apt-get install pngquant
          echo "::endgroup::"
        
      - name: Run
        run: find ./jekyll/assets/images -name "*.png" -not -name "*-opti.png" -exec pngquant --ext -opti.png {} \;
        
      - name: Clean previous image
        run: find ./jekyll/assets/images/ -name "*.png" -not -name "*-opti.png" -exec rm {} \;

      - name: Upload compressed image
        uses: actions/upload-artifact@v2
        with:
          name: compressed-png
          path: jekyll/assets/images

      - name: Upload to branch workflow_dispatch
        uses: ./.github/actions/upload-to-branch
        with:
          target-branch: ${{ github.event.target-branch }}
          user-name: ${{ secrets.BOT_ACCOUNT_NAME }}
          user-email: ${{ secrets.BOT_ACCOUNT_MAIL }}
        if: ${{ success() && github.event_name != 'workflow_run' && github.event.inputs.create-request-pull == 'true' }}

      - name: Upload to branch on workflow_run
        uses: ./.github/actions/upload-to-branch
        with:
          target-branch: workflow-${{ github.sha }}
          add-pattern: "*.png"
          user-name: ${{ secrets.BOT_ACCOUNT_NAME }}
          user-email: ${{ secrets.BOT_ACCOUNT_MAIL }}
        if: ${{ success() && github.event_name == 'workflow_run' }}
    
  compress-jpg:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Github checkout
        uses: actions/checkout@v2

      - name: Download
        run: |
          echo "::group::download"
          curl -L https://github.com/google/guetzli/archive/v1.0.1.tar.gz | tar zx
          sudo apt-get install libpng-dev
          echo "::endgroup::"
          
      - name: Install
        run: |
          echo "::group::installation"
          cd guetzli-1.0.1 && make
          echo "::endgroup::"
          
      - name: Run
        run: |
          echo "::group::run"
          find jekyll/assets/images/ -name "*.jpg" ! -path "jekyll/assets/originals/*" -exec guetzli-1.0.1/bin/Release/guetzli --verbose {} {} \;
          echo "::endgroup::"
        
      - name: Upload compressed image
        uses: actions/upload-artifact@v2
        with:
          name: compressed-jpg
          path: jekyll/assets/images
          
      - name: Upload to branch workflow_dispatch
        uses: ./.github/actions/upload-to-branch
        with:
          target-branch: ${{ github.event.target-branch }}
          user-name: ${{ secrets.BOT_ACCOUNT_NAME }}
          user-email: ${{ secrets.BOT_ACCOUNT_MAIL }}
        if: ${{ success() && github.event_name != 'workflow_run' && github.event.inputs.create-request-pull == 'true' }}
        
      - name: Upload to branch on workflow_run
        uses: ./.github/actions/upload-to-branch
        with:
          target-branch: workflow-${{ github.sha }}
          add-pattern: "*.jpg"
          user-name: ${{ secrets.BOT_ACCOUNT_NAME }}
          user-email: ${{ secrets.BOT_ACCOUNT_MAIL }}
        if: ${{ success() && github.event_name == 'workflow_run' }}
