name: Convert to webp

on:
  push:
    branches: [ release ]

  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    env:
      TARGET_FOLDER: "jekyll/assets/webp"
    steps:
      - name: Github checkout
        uses: actions/checkout@v2
        
      - name: Remove previous folder if necessary and create it
        run: |
          echo "::group::create webp folder"
          echo "Remove all webp folder"
          if [[ -d ${{ env.TARGET_FOLDER }} ]]; then
            rm -vrf ${{ env.TARGET_FOLDER }}
          fi
          mkdir ${{ env.TARGET_FOLDER }}
          echo "::endgroup::"
        shell: bash
        
      - name: Create webp jpg images
        id: create-webp-jpg-images
        uses: ./.github/actions/webp
        with:
          target-folder: ${{ env.TARGET_FOLDER }}
          original-folder: "jekyll/assets/originals"
          extensions-regex: "jpg"
          
      - name: Create webp png images
        id: create-webp-png-images
        uses: ./.github/actions/webp
        with:
          target-folder: ${{ env.TARGET_FOLDER }}
          original-folder: "jekyll/assets/originals"
          extensions-regex: "png"
          
      - name: Upload webp folders through artifacts
        uses: actions/upload-artifact@v1
        with:
          name: webp-images
          path: ${{ env.TARGET_FOLDER }}
        if: |
          ${{ steps.create-webp-jpg-images.outcome }} == "success" &&
          ${{ steps.create-webp-png-images.outcome }} == "success"
        
      # Should ALWAYS be the last step.
      - name: Teleconsole launch
        if: ${{ failure() }}
        run: echo "Should launch teleconsole and wait for it to be over."
