#############################################################################
# Grégoire Boiron <gregoire.boiron@gmail.com>
# Copyright (c) 2018-2021 Grégoire Boiron  All Rights Reserved.
#############################################################################

name: Convert to webp

on:
  workflow_run:
    workflows: ["Resize Images"]
    branches: [develop]
    types: 
      - completed

  workflow_dispatch:
    inputs:
      create-request-pull:
        description: 'Create request pull'
        required: true
        default: 'false'
      use-sha:
        description: 'Use GitHub sha'
        required: true
        default: 'true'

jobs:
  convert:
    runs-on: ubuntu-latest
    env:
      TARGET_FOLDER: "jekyll/assets/webp"
    steps:
      - name: Github checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
        
      - name: Remove previous folder if necessary and create it
        run: |
          echo "::group::create webp folder"
          echo "Remove all webp folder"
          if [[ -d ${{ env.TARGET_FOLDER }} ]]; then
            rm -vrf ${{ env.TARGET_FOLDER }}
          fi
          mkdir ${{ env.TARGET_FOLDER }}
          echo "IMAGE_PATH=jekyll/assets/originals" >> $GITHUB_ENV
          echo "::endgroup::"
        shell: bash
        if: ${{ github.event_name != 'workflow_run' && github.event.inputs.use-sha == 'false' }}
        
      - name: Build file from github sha Test1
        run: |
          echo ${{ github.sha }}
          git log --name-only -n 1 ${{ github.sha }} --pretty="format:" ${{ github.GITHUB_REF }} > last-commit.txt
          cat last-commit.txt
          PATH=$(find last-commit.txt -regextype posix-extended -regex "^.*\.[png|jpg]$")	
          echo $PATH	
          echo "IMAGE_PATH=$PATH" >> $GITHUB_ENV
        shell: bash
        if: ${{ github.event_name == 'workflow_run' || github.event.inputs.use-sha == 'true' }}
        
      - name: Create webp jpg images
        id: create-webp-jpg-images
        uses: ./.github/actions/webp
        with:
          target-folder: ${{ env.TARGET_FOLDER }}
          original-folder: ${{ env.IMAGE_PATH }}
          extensions-regex: "jpg"
          
      - name: Create webp png images
        id: create-webp-png-images
        uses: ./.github/actions/webp
        with:
          target-folder: ${{ env.TARGET_FOLDER }}
          original-folder: ${{ env.IMAGE_PATH }}
          extensions-regex: "png"
          
      - name: Upload webp folders through artifacts
        uses: actions/upload-artifact@v1
        with:
          name: webp-images
          path: ${{ env.TARGET_FOLDER }}
        if: |
          ${{ steps.create-webp-jpg-images.outcome }} == "success" &&
          ${{ steps.create-webp-png-images.outcome }} == "success"


      - name: Upload to branch
        uses: ./.github/actions/upload-to-branch
        with:
          target-branch: ${{ github.ref }}
          user-name: ${{ secrets.BOT_ACCOUNT_NAME }}
          user-email: ${{ secrets.BOT_ACCOUNT_MAIL }}
        if: ${{ github.event.inputs.create-request-pull == 'true' }}
        
      # Should ALWAYS be the last step.
      - name: Teleconsole launch
        if: ${{ failure() }}
        run: echo "Should launch teleconsole and wait for it to be over."
