name: Basic CI on push

on:
  push:
    branches:
      - develop

env:
  NOKOGIRI_USE_SYSTEM_LIBRARIES: true

jobs:
  setup:
    name: Setup in order to run jekyll commands
    runs-on: ubuntu-16.04
    defaults:
      run:
        shell: bash
        working-directory: ./jekyll
    steps:
      - name: Github checkout
        uses: actions/checkout@v2   # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      # Cache dependencies: will attempt to restore a cache based on the key you provide.
      # shorten build times and decrease load on servers.
      # see https://github.com/actions/cache/blob/main/examples.md#ruby---bundler
      - name: Github cache
        uses: actions/cache@v2
        with:
          path: |
            vendor/bundle
            ${{ env.GITHUB_REPOSITORY }}/tmp/.htmlproofer
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: | 
            ${{ runner.os }}-gems-

      - name: Github Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      # Make sure path match the one declared in actions/cache
      - name: Install Bundler
        uses: ./.github/actions/install
        with:
          bundle_path: vendor/bundle

      - name: Check files changed
        run: git log --name-only -n 1 ${{ github.sha }} --pretty=format:%b > last-commit.txt;
        if: ${{ github.event_name }} != "pull_request"

      - name: Upload file changed output
        uses: actions/upload-artifact@v1
        with:
          name: output-txt-file
          path: last-commit.txt
          
  build:
    name: Build
    runs-on: ubuntu-16.04
    needs: setup
    defaults:
      run:
        shell: bash
    steps:
      - name: Github Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Github checkout
        uses: actions/checkout@v2

      - name: jekyll-production-build
        uses: ./.github/actions/jekyll-build
        with:
          bundle-path: vendor/bundle
          project-folder: ./jekyll
          environment: production
          destination-relative-folder: site

      - name: Upload build through artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: jekyll/site/
        if: ${{ success() }}
  
  tests:
    name: Tests
    runs-on: ubuntu-16.04
    needs: build
    defaults:
      run:
        shell: bash
    steps:
      - name: Github Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Github checkout
        uses: actions/checkout@v2
        
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build/

      - name: html-proofer
        uses: ./.github/actions/html-proofer
        with:
          bundle-path: vendor/bundle
          bundle-folder: ./jekyll
          html-relative-folder: ../build
          url-ignore: "https://www.linkedin.com/in/gregoire-boiron/,https://www.latecoere.aero/en/"
