name: Convert to webp

on:
  push:
    branches: [ release ]

  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v2
        
      - name: Create webp images
        id: create-webp-images
        uses: ./.github/actions/webp
        with:
          target-folder: "jekyll/assets/webp"
          original-folder: "jekyll/assets/originals"
          extensions: "[jpg, png]"
          
      - name: Upload webp folders through artifacts
        uses: actions/upload-artifact@v1
        with:
          name: webp-images
          path: ${{ steps.create-webp-images.outputs.webp-folder }}
        if: ${{ steps.create-webp-images.outcome == "sucess" }}
        
      # Should ALWAYS be the last step.
      - name: Teleconsole launch
        if: ${{ failure() }}
        run: echo "Should launch teleconsole and wait for it to be over."
