name: Test Get latest commit

on:
  workflow_run:
    workflows: ["Test2"]
    branches: [develop]
    types: 
      - completed

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      
      - name: Test 1
        run: git log --name-only -n 1 --pretty="format:" origin/develop
      
      - name: Check files changed
        run: echo ${{ github.sha }}
      
      - name: Test 2
        run: git log --name-only -n 1 ${{ github.sha }} --pretty="format:" ${{ github.GITHUB_REF }}
        
      - name: Test 3
        run: git diff --name-only refs/heads/develop refs/heads/develop^
