# This is a basic workflow to help you get started with Actions

# Controls when the action will run. Triggers the workflow on push or pull request
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# Steps represent a sequence of tasks that will be executed as part of the job

name: CI

# Specify the controls here
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# Specify the workflow here
jobs:
  # =============================
  setup:
    runs-on: ubuntu-16.04
    steps:
      - name: Github checkout
        uses: actions/checkout@v2   # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      # Cache dependencies: will attempt to restore a cache based on the key you provide.
      # shorten build times and decrease load on servers.
      # see https://github.com/actions/cache/blob/main/examples.md#ruby---bundler
      - name: Github cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**  /Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

  # =============================
  install:
    needs: setup
    runs-on: ubuntu-16.04
    steps:
      - name: Move to right folder
        run: |
          echo $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE/jekyll

      - name: Github Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      # Make sure path match the one declared in actions/cache
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Pre-processes
        run: gem install bundler

  # =============================
  build:
    needs: install
    runs-on: ubuntu-16.04
    steps:
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
