name: Generate Markdown

on:
  push:
    branches: [ release ]

  workflow_dispatch:

jobs:

  generation:
    runs-on: ubuntu-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: generate-markdown
        run: |
          python ./.github/scripts/generation/githubProjectGen.py ${{ secrets.GENERATION_TOKEN }}
          git status

      - name: Upload front matters generation through artifacts
        uses: actions/upload-artifact@v1
        with:
          name: front-matter-gen
          path: jekyll/_includes/projects-front-matter/

      - name: Upload pages generation through artifacts
        uses: actions/upload-artifact@v1
        with:
          name: project-pages
          path: jekyll/collections/_project-pages/

      # TODO: We should create an artifact of the full project to delegate the rest to another job

      - name: Create GitHub PR
        run: |
          branch="github-build-$GITHUB_RUN_ID"
          git checkout -b $branch
          git config user.email ${{ secrets.BOT_ACCOUNT_MAIL }}
          git config user.name ${{ secrets.BOT_ACCOUNT_NAME }}
          git pull
          git add .
          git commit -m "[ignore] Upload files generate by the job #${{ env.GITHUB_RUN_ID }} ${{ env.GITHUB_ACTION }}"
          git push origin HEAD:$branch
          git request-pull develop "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"

