name: Generate Markdown

on:
  create:
    branches: [ release ]

  workflow_dispatch:

jobs:
  generation:
    runs-on: ubuntu-latest

    steps:
      - name: Github checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: generate-markdown
        run: |
          python ./.github/scripts/generation/githubProjectGen.py ${{ secrets.GENERATION_TOKEN }}
          git status

      - name: Upload front matters generation through artifacts
        uses: actions/upload-artifact@v1
        with:
          name: front-matter-gen
          path: jekyll/_includes/projects-front-matter/

      - name: Upload pages generation through artifacts
        uses: actions/upload-artifact@v1
        with:
          name: project-pages
          path: jekyll/collections/_project-pages/
