name: Resize Images

on:
  push:
    branches: [ release ]
    
  workflow_dispatch:

jobs:

  resize:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Github checkout
        uses: actions/checkout@v2

      - name: Create webp from jpg images
        uses: ./.github/actions/resizeimg
        with:
          original-folder: "jekyll/assets/"
          extension: "jpg"

      - name: Create webp from png images
        uses: ./.github/actions/resizeimg
        with:
          original-folder: "jekyll/assets/"
          extension: "png"

