#############################################################################
# Grégoire Boiron <gregoire.boiron@gmail.com>
# Copyright (c) 2018-2021 Grégoire Boiron  All Rights Reserved.
#############################################################################

name: Resize Images

on:
  push:
    branches: [ develop ]
    paths:
      - '**.jpg'
      - '**.png'

  workflow_dispatch:
    inputs:
      create-request-pull:
        description: 'Create request pull'
        required: true
        default: 'false'
      use-sha:
        description: 'Use GitHub sha'
        required: true
        default: 'true'
      target-branch:
        description: 'Branch to upload to'
        required: false
        default: 'develop'

jobs:

  resize:
    runs-on: ubuntu-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Cache image magick
        id: cache-image-magick
        uses: actions/cache@v2
        with:
          path: imagemagick
          key: ${{ runner.os }}-imagemagick
        
      - name: Build file from github sha Test1
        id: build-file-sha
        run: |
          git log --name-only -n 1 ${{ github.sha }} --pretty="format:" ${{ github.GITHUB_REF }} > last-commit.txt
          grep -E '^jekyll/assets/originals.*[\[r[0-9]+x[0-9]+\]|\[c[0-9]+x[0-9]+\]]\.png|jpg$' last-commit.txt > image-paths.txt
          cat image-paths.txt
        if: ${{ github.event_name == 'push' || github.event.inputs.use-sha == 'true' }}
      
      ###

      - name: Build file from original folder
        id: build-file
        run: |
          find jekyll/assets/originals -regextype posix-extended -regex "^.*\[[r|c][0-9]+x[0-9]+\]\..{3}$" > image-paths.txt
          cat image-paths.txt
        if: ${{ github.event_name != 'push' && github.event.inputs.use-sha == 'false' }}

      - name: Install image magick
        uses: ./.github/actions/install-imagemagick
        with:
          install-folder: imagemagick
        if: ${{ (steps.build-file-sha.outcome == 'success' || steps.build-file.outcome == 'success') && steps.cache-image-magick.outputs.cache-hit != 'true' }}

      - name: Resize images
        uses: ./.github/actions/resize-img
        with:
          images-names-file: image-paths.txt
        if: ${{ steps.build-file-sha.outcome == 'success' || steps.build-file.outcome == 'success' }}

      - name: Upload resize image
        uses: actions/upload-artifact@v1
        with:
          name: resized-image
          path: jekyll/assets/

      - name: Upload to branch workflow dispatch
        uses: ./.github/actions/upload-to-branch
        with:
          target-branch: ${{ github.event.target-branch }}
          user-name: ${{ secrets.BOT_ACCOUNT_NAME }}
          user-email: ${{ secrets.BOT_ACCOUNT_MAIL }}
        if: ${{ success() && github.event_name != 'push' && github.event.inputs.create-request-pull == 'true' }}

      - name: Upload to branch on push
        uses: ./.github/actions/upload-to-branch
        with:
          target-branch: workflow-${{ GITHUB_SHA }}
          add-pattern: "*.jpg *.png"
          user-name: ${{ secrets.BOT_ACCOUNT_NAME }}
          user-email: ${{ secrets.BOT_ACCOUNT_MAIL }}
        if: ${{ success() && github.event_name == 'push' }}
