#############################################################################
# Grégoire Boiron <gregoire.boiron@gmail.com>
# Copyright (c) 2018-2021 Grégoire Boiron  All Rights Reserved.
#############################################################################

name: Resize Images

on:
  push:
    branches: [ develop ]
    paths:
    - '**.jpg'
    - '**.png'

  workflow_dispatch:
    inputs:
      create-request-pull:
        description: 'Create request pull'
        required: true
        default: 'false'

jobs:

  resize:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Github checkout
        uses: actions/checkout@v2

      - name: Resize jpg images
        uses: ./.github/actions/resizeimg
        with:
          original-folder: "jekyll/assets/"
          extension: "jpg"

      - name: Resize png images
        uses: ./.github/actions/resizeimg
        with:
          original-folder: "jekyll/assets/"
          extension: "png"

      - name: Upload resize image
        uses: actions/upload-artifact@v1
        with:
          name: resized-image
          path: jekyll/assets/

      - name: Upload to branch
        uses: ./.github/actions/upload-to-branch
        with:
          target-branch: develop
          user-name: ${{ secrets.BOT_ACCOUNT_NAME }}
          user-email: ${{ secrets.BOT_ACCOUNT_MAIL }}
        if: ${{ github.event.inputs.create-request-pull == 'true' }}
