#############################################################################
# Grégoire Boiron <gregoire.boiron@gmail.com>
# Copyright (c) 2018-2021 Grégoire Boiron  All Rights Reserved.
#############################################################################

name: Resize Images

on:
  push:
    branches: [ develop ]
    paths:
      - '**.jpg'
      - '**.png'

  workflow_dispatch:
    inputs:
      create-request-pull:
        description: 'Create request pull'
        required: true
        default: 'false'
      use-sha:
        description: 'Create request pull'
        required: true
        default: 'true'

jobs:

  resize:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Github checkout
        uses: actions/checkout@v2
        
      - name: Build file from github sha
        run: |
          echo ${{ github.sha }}
          git log --name-only -n 1 ${{ github.sha }} --pretty=format:%b > last-commit.txt
          cat last-commit.txt
          PATH=$(find last-commit.txt -regextype posix-extended -regex "^.*\[[r|c][0-9]+x[0-9]+\]+\..{3}$")
          echo $PATH
          echo "IMAGE_PATH=$PATH" >> $GITHUB_ENV
        if: ${{ github.event.inputs.use-sha == 'true' || github.event_name == 'push' }}
        
      - name: Build file from github sha
        run: |
          PATH=$(find jekyll/assets/originals -regex ".*\[[r|c][0-9]+x[0-9]+\]+\..{3}$")
          echo $PATH
          echo "IMAGE_PATH=$PATH" >> $GITHUB_ENV
        if: ${{ github.event.inputs.use-sha == 'false' || github.event_name != 'push' }}

      - name: Resize png images
        uses: ./.github/actions/resize-img
        with:
          images-names-file: ${{ env.IMAGE_PATH }}
        if: ${{ env.IMAGE_PATH != '' }}

      - name: Upload resize image
        uses: actions/upload-artifact@v1
        with:
          name: resized-image
          path: jekyll/assets/
        if: ${{ env.IMAGE_PATH != '' }}

      - name: Upload to branch
        uses: ./.github/actions/upload-to-branch
        with:
          target-branch: ${{ github.ref }}
          user-name: ${{ secrets.BOT_ACCOUNT_NAME }}
          user-email: ${{ secrets.BOT_ACCOUNT_MAIL }}
        if: ${{ env.IMAGE_PATH != '' && github.event.inputs.create-request-pull == 'true' }}
